#!/bin/bash

#Check that valid argument wa entered
if [ "$#" -ne 1 ]; then
	echo "usage: ./02 USERNAME"
	exit 0
fi

#Check that argument corresponds to an existing user
if [ -z "$(cat /etc/passwd | grep "$1:")" ]; then
	echo "User "$1" does not exist"
	exit 0
fi

#Check that argument corresponds to a logged user
if [ -z "$(who | grep "$1 ")" ]; then
	echo "User "$1" is not logged in"
	exit 0
fi

#Block user
sudo passwd -l "$1"

#Close processus launched by the user
PID="$(pgrep -u "$1" | wc | cut -b -7 | sed "s/ //g")"
if [ ${PID} != 0 ]; then
	sudo killall -KILL -u "$1"
fi

#Delete cron tasks
sudo crontab -r -u "$1"

#Delete the user
sudo userdel -r "$1"
